name: Build ChatGLM base
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main # Push events on master branch
    # Sequence of patterns matched against refs/tags
    tags:
      - "**"             # Push events to v1 tag
jobs:
  chatglm:
    name: ChatGLM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hjin/chatglm
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: chatglm
          tag_names: true