name: Build Chrome Node
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - chrome # Push events on master branch
    # Sequence of patterns matched against refs/tags
    tags:
      - "**"             # Push events to v1 tag
jobs:
  chrome-node:
    name: Node with Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hjin/chrome
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: chrome
          tag_names: true
          snapshot: true