name: Build Dioxus Cli
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - dioxus-build # Push events on master branch
    # Sequence of patterns matched against refs/tags
    tags:
      - "**"             # Push events to v1 tag
jobs:
  dioxus-build:
    name: Rust Wasm With Dioxus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hjin/dioxus-build
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: dioxus-build
          tag_names: true
          snapshot: true
