name: Build Cargo Leptos
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - leptos-build # Push events on master branch
    # Sequence of patterns matched against refs/tags
    tags:
      - "**"             # Push events to v1 tag
jobs:
  leptos-build:
    name: Rust Nightly Wasm With Cargo-Leptos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
      - name: Publish to Registry
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hjin/leptos-build
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: leptos-build
          tag_names: true
#          platforms: linux/amd64,linux/arm64
          snapshot: true
